modLoader = "javafml"
loaderVersion = "[46,)"
license = "Custom"

[[mods]]
modId = "meadow"
version = "${version}"
displayName = "[Let's Do] Meadow"
authors = ["satisfy", "Cristelknight999", "BMJO"]
description = '''
Hey Wanderer! Sit down, enjoy a piece of cheese, and take a look at the new mountain pasture - cliffs, beautiful forests, clearings, and lots of colorful flowers.
'''
logoFile = "pack.png"

[[dependencies.meadow]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.meadow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.meadow]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.meadow]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.13,)"
ordering = "AFTER"
side = "BOTH"